development:
  adapter: mysql2
  encoding: utf8
  database: db
  username: root
  password:
  host: 127.0.0.1
  port: 3306
  pool: 25

test: &test
  adapter: mysql2
  database: test<%= ENV['TEST_ENV_NUMBER'] %>
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  port: <%= t_port %>
<% else %>
test: &test
  adapter: mysql2
  database: test<%= ENV['TEST_ENV_NUMBER'] %>
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  port: 3306
<% end %>

production:
  adapter: mysql2
  encoding: utf8
  database: production
  username: root
  password:
  host: 127.0.0.1
  port: 3306