development:
  adapter: mysql2
  encoding: utf8
  database: db
  username: root
  password:
  host: 127.0.0.1
  port: 3306
  pool: 25

test:
  adapter: mysql2
  database: test
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  port: 6379

production:
  adapter: mysql2
  encoding: utf8
  database: production
  username: root
  password:
  host: 127.0.0.1
  port: 3306
